import type { AppRevealPreset } from './presetTypes';

export const BUILTIN_PRESETS: AppRevealPreset[] = [
  {
    schemaVersion: 1,
    id: 'builtin-sns-shorts',
    name: '📱 SNSショート・インパクト',
    description: '縦型9:16で中心から一気に高解像度化するShorts/Reels向けアイキャッチ',
    createdAt: '2026-09-17T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
    isBuiltin: true,
    canvas: {
      aspectRatio: '9:16',
      fit: 'cover',
      positionOffset: { x: 0, y: 0 },
      backgroundColor: '#000000',
      transparent: false,
    },
    animation: {
      mode: 'radial_out',
      duration: 2.5,
      startDelay: 0.3,
      holdTime: 1.2,
      mosaicSize: 48,
      feather: 0.15,
      easing: 'cubic',
      loop: true,
      seed: 12345,
    },
    exportSettings: {
      resolutionPreset: '720p',
      fps: 30,
      format: 'mp4',
    },
  },
  {
    schemaVersion: 1,
    id: 'builtin-cinematic-scan',
    name: '🎬 シネマティック・スキャン',
    description: '横型16:9、24fpsのフィルムライクな上から下へのプログレッシブ走査',
    createdAt: '2026-09-17T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
    isBuiltin: true,
    canvas: {
      aspectRatio: '16:9',
      fit: 'contain',
      positionOffset: { x: 0, y: 0 },
      backgroundColor: '#050505',
      transparent: false,
    },
    animation: {
      mode: 'linear_scan',
      duration: 3.5,
      startDelay: 0.5,
      holdTime: 1.0,
      mosaicSize: 40,
      feather: 0.25,
      easing: 'easeInOut',
      loop: true,
      seed: 9999,
    },
    exportSettings: {
      resolutionPreset: '1080p',
      fps: 24,
      format: 'mp4',
    },
  },
  {
    schemaVersion: 1,
    id: 'builtin-retro-lod',
    name: '👾 レトロゲームLOD (GIF最適)',
    description: '粗いモザイクから徐々にドットが細かくなるドット絵・レトロゲーム調',
    createdAt: '2026-09-17T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
    isBuiltin: true,
    canvas: {
      aspectRatio: '1:1',
      fit: 'contain',
      positionOffset: { x: 0, y: 0 },
      backgroundColor: '#111827',
      transparent: false,
    },
    animation: {
      mode: 'multi_step_lod',
      duration: 3.0,
      startDelay: 0.5,
      holdTime: 1.0,
      mosaicSize: 64,
      feather: 0.0,
      easing: 'linear',
      loop: true,
      seed: 1111,
      lodSteps: 5,
      lodSmooth: false,
    },
    exportSettings: {
      resolutionPreset: '720p',
      fps: 15,
      format: 'gif',
      gifPaletteMode: 'per-frame',
    },
  },
  {
    schemaVersion: 1,
    id: 'builtin-puzzle-block',
    name: '🧩 パズルブロック・リビール',
    description: '正方形グリッドがランダム順にパズルのように解けていく演出',
    createdAt: '2026-09-17T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
    isBuiltin: true,
    canvas: {
      aspectRatio: '1:1',
      fit: 'contain',
      positionOffset: { x: 0, y: 0 },
      backgroundColor: '#000000',
      transparent: false,
    },
    animation: {
      mode: 'random_reveal',
      duration: 3.2,
      startDelay: 0.4,
      holdTime: 1.0,
      mosaicSize: 48,
      feather: 0.1,
      easing: 'easeOut',
      loop: true,
      seed: 77777,
      gridSize: 16,
    },
    exportSettings: {
      resolutionPreset: '720p',
      fps: 30,
      format: 'mp4',
    },
  },
  {
    schemaVersion: 1,
    id: 'builtin-cyber-scan',
    name: '⚡ サイバースキャン・ノイズ',
    description: 'スキャンライン進行とランダムブロックノイズが飛び出るSF調',
    createdAt: '2026-09-17T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
    isBuiltin: true,
    canvas: {
      aspectRatio: '9:16',
      fit: 'cover',
      positionOffset: { x: 0, y: 0 },
      backgroundColor: '#000000',
      transparent: false,
    },
    animation: {
      mode: 'block_scan',
      duration: 2.2,
      startDelay: 0.2,
      holdTime: 1.0,
      mosaicSize: 32,
      feather: 0.15,
      easing: 'cubic',
      loop: true,
      seed: 42424,
      gridSize: 32,
      noiseStrength: 0.65,
    },
    exportSettings: {
      resolutionPreset: '720p',
      fps: 60,
      format: 'mp4',
    },
  },
];
